name: Run on AWS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: [ '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyver }}
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          make install
      - name: Linting
        run: |
          make lint
      - name: Testing
        run: |
          make testing